# Generated by Django 3.1 on 2020-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Uni', models.CharField(max_length=100)),
                ('GPA', models.FloatField(default=0.0)),
            ],
        ),
    ]
